name: Check Nodes

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: write

jobs:
  check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable IPv6 with WARP
        run: |
          sudo apt update
          sudo apt install -y wireguard resolvconf

          wget -q https://github.com/ViRb3/wgcf/releases/download/v2.2.32/wgcf_2.2.32_linux_amd64 -O wgcf
          chmod +x wgcf
          sudo mv wgcf /usr/local/bin/

          wgcf register --accept-tos
          wgcf generate

          sudo mkdir -p /etc/wireguard
          sudo cp wgcf-profile.conf /etc/wireguard/wgcf.conf

          sudo chmod 600 /etc/wireguard/wgcf.conf

          sudo wg-quick up wgcf

      - name: Test IPv4
        run: |
          echo "IPv4 connectivity:"
          curl -4 https://api.ipify.org

      - name: Test IPv6
        run: |
          echo "IPv6 address:"
          ip -6 addr

          echo "IPv6 connectivity:"
          curl -6 https://api64.ipify.org

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Xray
        run: |
          curl -L \
            --retry 5 \
            --retry-delay 5 \
            --retry-all-errors \
          https://github.com/XTLS/Xray-core/releases/download/v26.3.27/Xray-linux-64.zip -o xray.zip
          unzip -oq xray.zip xray
          chmod +x xray
          sudo mv xray /usr/local/bin/

      - name: Check Version
        run: |
          python --version
          xray version
          curl --version

      - name: Create Directories
        run: |
          mkdir -p public
          mkdir -p data

      - name: Check Nodes
        run: |
          python scripts/check_node.py

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add public data

          if git diff --cached --quiet; then
            echo "Nothing changed."
            exit 0
          fi

          git commit -m "Update node list"

          git push
